### PR TITLE
Saved property landlord UI

### PR DESCRIPTION
**Pull request by mluo24**
### Summary 

This pull request introduces a new feature to enhance user profiles by enabling the saving and management of favorite apartments. The main additions include the implementation of an expand and collapse button for saved apartments within the user profile and the incorporation of a dedicated endpoint to fetch saved properties (as I don't believe it existed before).

- Created new saved apartment component
- Added an expand and collapse button for saved apartments in the user profile.
- Created a new API endpoint (/api/get-saved-apartments) to retrieve saved properties for a user.

### Test Plan 

image

### Notes 

Currently does not have the correct data. Also there may be some mobile formatting issues.

### CODE REVIEW

**Review by thuypham03 — APPROVED** [review]
Good job on creating new component for bookmark page. This PR creates a foundation for the upcoming tasks in the future:
1. Enable save/unsave feature in the bookmarkAptCard --> Should handle onClick function
2. Also show saved landlords, now only saved apartments are shown

**Review by AnkitLakkapragada — COMMENTED** [review]
Awesome work Miranda! These changes are definitely super needed and will really improve the user experience. I will say that for the backend api you created, surrounding it in a try/catch might make it a little safer. Also, deleting the token as it isn't used in the BookmarksPage.tsx. Overall great work and looking forward to seeing this PR merged soon!

**Review by thuypham03 — APPROVED** [review]
LGTM!

**Review by thuypham03 — APPROVED** [review]
LGTM!

**Pull request merged**
