### PR TITLE
Implemented the Review Approval Email System

### PR DESCRIPTION
**Pull request by kea-roy**
### Background
After a user submits a review, there is no notification system to notify the user that their review has been approved by an admin. The implemented review approval email system aims to resolve this issue in the user experience.

With this pull request, once an admin approves a review, the user who submitted the review is notified by email.

### Changes

This pull request contains the following changes:
- [x] The design of the email
- [x] adding the nodemailer dependency to send the email through gmail smtp
- [x] referencing two new environment variables: CUAPTS_EMAIL and CUAPTS_APP_EMAIL_PASSWORD
- [x] getting the user's email address from the review and using nodemailer to send an email to the user.
- [x] Added documentation to update-review-status endpoint.
- [x] Added security measures to ensure the user is an admin (based on homeconsts.ts) before approving/declining/deleting a review. (Any logged-in user can currently switch review status to pending.)
- [x] Fixed typo in a function name in Review.tsx: reportAbuseHanler to reportAbuseHandler
- [x] Accounted for edge cases to avoid sending duplicate emails: where the review is already approved and the API requests for the review to be updated to approved status again.
- [x] Fixed authentication header not being passed to the update-review-status put request.
- [x] Added and improved documentation in app.ts and auth.ts to make it easier to understand.
- [x] Adjusted AdminReview.tsx to account for the API changes to update-review-status by passing user authentication parameters.
- [x] Fixed authentication header not being passed to the update-review-status put request in Review.tsx.

## Test Plan 

I created several fake reviews on the dev build to send test emails.
Since CUApts doesn't currently have an email, I used my own personal gmail account and password and stored the data in my local environment variables to mimic a CUApts email.

Below are screenshots of some of the test emails and their format, testing the appearance on different platforms.
### Apple Mail (When on light theme devices)
Screenshot 2024-03-15 at 16 03 37

### Apple Mail (When on dark theme devices)
Screenshot 2024-03-15 at 16 03 47

### Gmail
Important Notes: The CUApts logo is not there because SVG image files aren't supported on Gmail for security reasons. Google web fonts like "Work Sans" are also not available on Gmail for similar security reasons.
Screenshot 2024-03-15 at 16 04 52

### IMPORTANT
- To make the code work on your dev local copy: two environment variables must be added to env.dev:
```
# gmail config
CUAPTS_EMAIL= ##########@gmail.com
CUAPTS_EMAIL_APP_PASSWORD=################
```

-The code references files from the frontend folder, such as the list of admins, so running backend on its own may break after merging this PR.

### Future Plans
- Find a way to display CUApts logo in all mail apps, potentially by uploading CUApts logo to somewhere on the web, so it can be referenced.
- Create a CUApts email account, maybe using Gmail or some other domain.
- Change the way admin information is stored, currently it is stored in an editable file on the frontend, which is a huge security flaw.

### CODE REVIEW

**Comment by kea-roy** [comment]
## Commit Changes
- Added documentation to update-review-status endpoint.
- Added security measures to ensure the user is an admin (based on homeconsts.ts) before approving/declining/deleting a review. (Any logged-in user can currently switch review status to pending.) 
- Fixed typo in a function name in Review.tsx: reportAbuseHanler to reportAbuseHandler
- Accounted for edge cases to avoid sending duplicate emails: where the review is already approved and the API requests for the review to be updated to approved status again.

**Comment by kea-roy** [comment]
## Commit Changes
- Fixed authentication header not being passed to the update-review-status put request.
- Added and improved documentation in app.ts and auth.ts to make it easier to understand.
- Adjusted AdminReview.tsx to account for the API changes to update-review-status by passing user authentication parameters.

Tested using my own email address in env.dev and approving reviews through my admin account. The API call successfully passes all authentication checks and sends the email to the user.

**Comment by kea-roy** [comment]
## Commit Changes
- Fixed authentication header not being passed to the update-review-status put request in Review.tsx.

Tested using my own email address in env.dev and approving reviews through my admin account. The API call successfully passes all authentication checks when looking at a review on the apartment page.

**Review by dan-ieljin — APPROVED** [review]
Clean implementation and excellent documentation!

**Pull request merged**
