### PR TITLE
jiayuan added to the contributor list

### PR DESCRIPTION
**Pull request by jiayuangu762943**
### Summary 

- Add my name to the PR

### CODE REVIEW

**Review by cyrus14 — DISMISSED** [review]
Looks good! I liked the way you added your name.

**Review by samliu10 — DISMISSED** [review]
LGTM

**Review by samliu10 — APPROVED** [review]
LGTM

**Review by cyrus14 — APPROVED** [review]
Looks great!

**Comment by jiayuangu762943** [comment]
email not working

**Pull request closed without merging**
