### PR TITLE
[Small Change] Add Kea-Roy as Admin

### PR DESCRIPTION
**Pull request by kea-roy**
### Summary 

Small change to add email to admin list.

### CODE REVIEW

**Review by ggsawatyanon — DISMISSED** [review]
Can you add a comment with your name too? Thanks.

**Review by CasperL1218 — COMMENTED** [review]
Full names for the admins might be helpful.

**Comment by kea-roy** [comment]
## Changes Made
1. Added name comment

**Review by ggsawatyanon — APPROVED** [review]
Thanks for adding the comment with your name.

**Pull request merged**
