### PR TITLE
Display all review images instead of 1

### PR DESCRIPTION
**Pull request by ggsawatyanon**
### Summary 

This pull request displays all the images the user uploads to a review, unlike how previously only 1 image was displayed. 

- [x] fixed frontend bug where only 1 image was displayed in each review

### Test Plan 

1 and 2 pictures:
Screen Shot 2023-03-26 at 20 54 24
3 pictures:
Screen Shot 2023-03-26 at 20 54 10

### CODE REVIEW

**Review by AnkitLakkapragada — APPROVED** [review]
This pull request is very useful! It will definitely help with the UI experience of users. Good work!

**Comment by dan-ieljin** [comment]
Great job! The CSS is consistent and concise. The resulting UI is clean and fully functional. It will definitely improve the user experience.

**Comment by jesshan700** [comment]
Great job on this pull request :) This change definitely helps looking at the pictures easier for the user!

**Review by thuypham03 — APPROVED** [review]
LGTM! Congrats on completing your first PR, the CSS styling look clean to me!

**Pull request merged**
