### PR TITLE
Importing reviews and heart ratings to homepage apartment cards

### PR DESCRIPTION
**Pull request by thuypham03**
This PR close Issue #169 and adapt heart ratings

Issue resolved in this PR:
- Importing real comment into the apartment card ("No Review" if there's no available comments)
- Importing real average heart ratings into the apartment card
- Adapt the length of the card to span over the whole webpage

Picture of the current page:

Screen Shot 2022-10-15 at 3 43 28 PM

### CODE REVIEW

**Review by cyrus14 — DISMISSED** [review]
Hey Sophia! This PR was much needed on the homepage apartment cards as previously the ratings and reviews did not correspond with the apartment that was displayed. The site looks exactly like it's supposed to with your changes that you added. I did not see anything out of the ordinary. Looking through the edited code I saw that you passed in the the designated apartment reviews using useEffect, I thought this was well done and aligns with how this process is done in other parts of the codebase. Again, great job!

**Comment by dan-ieljin** [comment]
Hi Sophia, this PR looks great! The reviews and heart ratings make the user experience better, and the styling is well done. The code itself is also clean, with good use of types and hooks.

**Comment by juliejeong** [comment]
This is a nice touch to the details that enhances the user experience! The codes look coherent & clean and the website looks like the design. Nice job!

**Review by juliejeong — COMMENTED** [review]
This is a nice touch to the details that enhances the user experience! The codes look coherent & clean and the website looks like the design. Nice job!

**Review by cyrus14 — APPROVED** [review]
Hey Sophia! Just saw your new commit that fixed the length of the ApartmentCard this will be very useful for breakpoints. Great job!

**Pull request merged**
