### PR TITLE
Infinite Scrolling on Homepage

### PR DESCRIPTION
**Pull request by thuypham03**
This PR resolve issue #185 by adding infinite scrolling on homepage.

Steps: 
- Adding `loadingLength` in `frontend/src/constants/HomeConsts.ts`
- Modifying API `/page-data/:page/:size` and `/location/:loc/:size` in `backend/src/app.ts` by adding array size when loading data from database and returning `isEnded` (whether the collection query has been fully loaded)
- Create component `frontend/src/components/ApartmentCard/ScrollingCards.tsx` to handle the infinite scrolling, when reaching the bottom of the page, `dataSize` will be updated (`+ loadingLength`), causing the page to re-render to update the `data`
- Adding message 'Loading more apartments...' if it hasn't fully loaded, otherwise 'There's no more apartments!'

https://user-images.githubusercontent.com/62644357/198853212-2b91f330-b439-4c4e-8ca9-620bf7446366.mov

https://user-images.githubusercontent.com/62644357/202799047-7500fc62-e3e2-4924-ac60-26d54ead9d0d.mov

### CODE REVIEW

**Review by juliejeong — APPROVED** [review]
Nicely done! When tested locally, scrolling & loading more pages went smoothly and the codes look clean. One suggestion that could be added design-wise is maybe adding something like "load more" or some indication that there are more pages to be loaded. so that it is more clear & intuitive to the user since as of right now it's a bit subtle.

**Review by cyrus14 — COMMENTED** [review]
Hi Sophia! Great job on this PR to add infinite scrolling functionality to the homepage. I really like how you added what Julie suggested which was to show a "load more" indicator so that the user is able to intuitively expect more apartments to load. I think it's also great how you've abstracted the size of how many apartments to retrieve so that it is more versatile for future features we would want to add. Last thing to add, I think you could remove the 'page' variable on line 206 in backend/src/app.ts because it is never used.

**Review by juliejeong — COMMENTED** [review]
The new changes look great! Definitely more efficient and structured than the previous version. Scrolling looks flawless when tested locally! Nice job!

**Comment by dan-ieljin** [comment]
This PR for adding infinite scrolling looks great! The load more functionality is definitely a smart choice since it does not overwhelm the user with content. No issues when testing on my local machine. The new API endpoint also is cleanly implemented with intuitive code and error handling.

**Review by cyrus14 — APPROVED** [review]
Hi Sophia! I'm reviewing this PR for the second time after seeing the changes you made to your original PR. Just to reiterate really good job creating the infinite scrolling. This is very beneficial for our platform as a whole since we are dealing with so many listings. The load more indicator is good for users because they will understand that by scrolling they can load more listings. Also great job on removing unused variables. Approved!

**Pull request merged**
