### PR TITLE
Implement Delete Button to Admin Page

### PR DESCRIPTION
**Pull request by AnkitLakkapragada**
### Summary 

This pull request implements the delete button to the admin page for the declined section so that admin users can stop seeing reviews that they want to delete. 

PNG image
PNG image

### Test Plan 

Tested it locally.

### Breaking Changes  
None

### CODE REVIEW

**Comment by cyrus14** [comment]
Hey Ankit! Great job on this feature, I think you've made a valuable addition to our admin page with the delete button for the declined section. This enhancement will undoubtedly streamline the workflow for our admin users, making it easier for them to manage and declutter their review queues. Looking at the code I like how you don't have any redundancies and the functionality works great when I tested it. Again great job!

**Review by mluo24 — COMMENTED** [review]
Code looks good, and this feature works! I especially like that you made it a status rather than actually deleting it, as soft deletes are generally good practice. I also like how you reused the components for showing the reviews and just added an extra argument. A good solution!

Not sure what's up with your yarn file though, since there shouldn't be any changes as far as I'm aware.

**Comment by jesshan700** [comment]
This looks really good! The delete button is a really important feature when it comes to how users will view our product - it will definitely clean up a lot on the admin page.

**Review by thuypham03 — APPROVED** [review]
Good job on soft-delete practice!

**Pull request merged**
