### PR TITLE
Added new dev name

### PR DESCRIPTION
**Pull request by jesshan700**
Added new dev name - Jessica Han

### CODE REVIEW

**Review by cyrus14 — APPROVED** [review]
Congrats on your first PR!!!!!!

**Review by cyrus14 — DISMISSED** [review]
Hi Jessica, from looking at why the Deploy to Firebase Hosting on PR / build_and_preview (pull_request) failed, you have to use node version "16.x" instead of "18.14.1". This page may help: https://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js

**Review by thuypham03 — APPROVED** [review]
Congrats on your first PR on CUApts team! I have fixed the error in deployment of mismatching node version in ci/ cd, so no further action needed! Please take your time exploring CUApts codebase!

**Comment by ggsawatyanon** [comment]
Looks good this is already merged but, congrats on your first PR!!

**Pull request merged**
